(executable
 (name test)
 (libraries landmark)
 (enabled_if (>= %{ocaml_version} "5")))

(rule
 (enabled_if (>= %{ocaml_version} "5"))
 (action
  (ignore-stderr
   (with-stdout-to
    test.out
    (run ./test.exe)))))

(rule
 (alias runtest)
 (enabled_if
  (>= %{ocaml_version} "5"))
 (action
  (diff test.out.expected test.out)))
